### ISSUE TITLE
Refresh option on Settings->Outputs

### ISSUE THREAD

**Issue by MWCmax** [mwcproject/mwc-qt-wallet#1]
It would be nice to have a refresh option on the settings -> outputs page
As you do on the transactions page

**Comment by bayk** [comment]
Yes, good idea. Will implement.

**Comment by cgilliard** [comment]
One other note on this one, Martin and I noticed that when you are on the output tab, if you select it again, it hangs. You have to click on another tab to get back to the outputs.

**Comment by bayk** [comment]
Yesterday release should fix that.

**Comment by cgilliard** [comment]
Actually trying on yesterday's fix.

**Comment by cgilliard** [comment]
And it's still doing that for me.

**Comment by cgilliard** [comment]
Wait let me double check.

**Comment by cgilliard** [comment]
Confirmed in latest build that outputs page still doesn't refresh if you select it when you are already on the tab.

**Comment by bayk** [comment]
I see it. Waiting is never end if start pressing many times at that page. Will take look.

**Comment by bayk** [comment]
Fixed
