### ISSUE TITLE
Do better than:   500 Internal Server Error with data Body(Streaming)

### ISSUE THREAD

**Issue by forceways** [mwcproject/mwc-qt-wallet#136]
[mwcwallet.log](https://github.com/mwcproject/mwc-qt-wallet/files/3877940/mwcwallet.log)

**Comment by cgilliard** [comment]
I think the problem is with your mwc-wallet. Do you have your recovery phrase? If so, recover with the following:

# mkdir recover
# cd recover
# mwc-wallet init -h -r
phrase> enter your phrase here
# mwc-wallet restore

Then try to send the funds again via file to the mwc-qt-wallet

**Comment by forceways** [comment]
ok i try

**Comment by forceways** [comment]
i restore my wallet from phrase and send tx to qt wallet and he give me tx.response, then i try to finalize it and got this:
 >mwc-wallet finalize -i qt1.tx.response
Password: 20191122 07:58:00.405 ERROR grin_wallet_impls::node_clients::http - Post TX Error: Request error: Wrong response code: 500 Internal Server Error with data Body(Streaming)
20191122 07:58:00.405 ERROR grin_wallet_libwallet::api_impl::owner - api: post_tx: failed with error: Client Callback Error: Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body(Streaming)
20191122 07:58:00.406 ERROR grin_wallet_controller::command - Tx not sent: Client Callback Error: Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body(Streaming)
Wallet command failed: LibWallet Error: Client Callback Error: Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body(Streaming)

**Comment by forceways** [comment]
[qt1.tx.response.txt](https://github.com/mwcproject/mwc-qt-wallet/files/3878024/qt1.tx.response.txt)

**Comment by cgilliard** [comment]
Try restarting your full node and then finalize again.

**Comment by forceways** [comment]
ok

**Comment by forceways** [comment]
after restarting got this:
C:\Users\12-3\Downloads\mwc-node-2.4.3-win-x64\mwc\mwc-wallet-2.4.6-win-x64\mwc-wallet>mwc-wallet finalize -i qt1.tx.response
Password: Wallet command failed: LibWallet Error: Wallet store error: DB Not Found Error: Slate id: [ec, 92, 8f, e1, e3, 6, 42, 7e, ba, 60, 7b, 7c, 1b, 72, 52, e1]

**Comment by cgilliard** [comment]
Are you finalizing in the "restore" wallet?

**Comment by forceways** [comment]
yes

**Comment by cgilliard** [comment]
That error means it was sent from a different wallet than you are finalizing in.

**Comment by forceways** [comment]
ok i download ubuntu then....  windows is sucks....  i have one wallet in this mashine.....

**Comment by cgilliard** [comment]
Ok install a node on ubuntu too. I think the node is the problem.

**Comment by bayk** [comment]
Hi @cgilliard , @forceways  Node respond with "500 Internal Server Error with data Body(Streaming)"  if this slate is non valid. It can happen if you already finalized that transaction or output is already spent.  Also you might mess with a network.

**Comment by cgilliard** [comment]
I think it might be related to this:
https://github.com/mimblewimble/grin-wallet/issues/141 (they thought it was
fixed in 2.0+ but maybe not.

**Comment by bayk** [comment]
I think we need better error handling. Currently seems like it is
always this error it is not possible to post a slate. You easily to
simulate it by double posting. Submit command will return the same error

**Comment by cgilliard** [comment]
Agreed.

**Comment by bayk** [comment]
Update:  Fixed original issue with logs at mwc-wallet. 
20191122 07:58:00.405 ERROR grin_wallet_libwallet::api_impl::owner - api: post_tx: failed with error: Client Callback Error: Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body(Streaming)

QT wallet still not ready. Finalize need to be updated with error details

**Comment by bayk** [comment]
Let's keep it open, we need to update mwc713 and qt wallet with the same
